# Generated by Django 5.2.7 on 2026-09-07 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=50)),
                ('vehicle_type', models.CharField(choices=[('CAR', 'Car'), ('BIKE', 'Bike')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='parkingslot',
            name='parking_category',
            field=models.CharField(choices=[('OWNED', 'Owned Vehicle'), ('VISITOR', 'Visitor')], default='OWNED', max_length=20),
        ),
        migrations.AlterField(
            model_name='parkingslot',
            name='slot_type',
            field=models.CharField(choices=[('CAR', 'Car'), ('BIKE', 'Bike')], max_length=20),
        ),
        migrations.CreateModel(
            name='TemporaryParkingAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField(auto_now_add=True)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('OVERSTAY', 'Overstay')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parking_slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='temporary_allocations', to='parking.parkingslot')),
            ],
        ),
    ]
