# Generated by Django 5.2.7 on 2026-09-07 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_temporaryvehicle_parkingslot_parking_category_and_more'),
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporaryvehicle',
            name='gate_pass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_vehicles', to='visitors.gatepass'),
        ),
        migrations.AddField(
            model_name='temporaryparkingallocation',
            name='temporary_vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_allocations', to='parking.temporaryvehicle'),
        ),
    ]
