# Generated by Django 5.2.7 on 2026-09-03 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_homemembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='homemembership',
            name='can_access_billing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='homemembership',
            name='can_approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='homemembership',
            name='can_approve_gate_requests',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='homemembership',
            name='can_manage_members',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='homemembership',
            name='membership_role',
            field=models.CharField(choices=[('PRIMARY_OWNER', 'Primary Owner'), ('SECONDARY_MEMBER', 'Secondary Member'), ('TENANT', 'Tenant'), ('EXTENDED_HOUSEHOLD', 'Extended Household')], max_length=30),
        ),
    ]
