# Generated by Django 5.2.7 on 2026-09-04 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_householdinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='householdinvitation',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
