# Generated by Django 5.2.7 on 2026-09-09 03:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('purpose', models.CharField(choices=[('FORGOT_PASSWORD', 'Forgot Password'), ('LOGIN', 'Login Verification'), ('SECURE_LOGIN', 'Secure Login')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_otps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
