# Generated by Django 5.2.7 on 2026-09-08 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_householdinvitation_accepted_at'),
        ('notices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='is_urgent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notice',
            name='requires_acknowledgment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notice',
            name='target_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='target_type',
            field=models.CharField(choices=[('COMMUNITY', 'Community'), ('BLOCK', 'Block'), ('TOWER', 'Tower')], default='COMMUNITY', max_length=20),
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_type', models.CharField(choices=[('COMMUNITY', 'Community'), ('BLOCK', 'Block'), ('TOWER', 'Tower')], default='COMMUNITY', max_length=20)),
                ('target_name', models.CharField(blank=True, max_length=100, null=True)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('event_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='community.community')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_announcements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NoticeAcknowledgment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acknowledged_at', models.DateTimeField(auto_now_add=True)),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgments', to='notices.notice')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notice_acknowledgments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
