# Generated by Django 5.2.7 on 2026-09-04 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0007_householdinvitation_accepted_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('max_booking_duration_minutes', models.PositiveIntegerField(default=60)),
                ('advance_booking_days', models.PositiveIntegerField(default=30)),
                ('monthly_booking_limit_per_home', models.PositiveIntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='community.community')),
            ],
        ),
        migrations.CreateModel(
            name='AmenityBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('NO_SHOW', 'No Show')], default='CONFIRMED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='amenities.amenity')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenity_bookings', to='community.home')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenity_bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
