# Generated by Django 5.2.7 on 2026-09-05 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amenities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenitybooking',
            name='admin_review_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='amenitybooking',
            name='admin_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='amenitybooking',
            name='booking_privilege_suspended',
            field=models.BooleanField(default=False),
        ),
    ]
