# Generated by Django 5.2.7 on 2026-09-03 06:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0003_permission_rolepermission'),
        ('community', '0005_homemembership_can_access_billing_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usercommunityrole',
            unique_together={('user', 'community')},
        ),
    ]
